[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  # Redireciona rotas de SPA para o index, mas ignora funções internas
  from = "/*"
  to = "/index.html"
  status = 200